### ISSUE TITLE
showgap for autolayer()?

### ISSUE THREAD

**Issue by conrad-mac** [tidyverts/fabletools#113]
Is there a plan to have a `showgap` parameter for `autolayer()` in this package?

**Comment by mitchelloharawild** [comment]
I'd definitely like to add support for this.
The challenge is that the fable object doesn't know what the last observed value is. We'd need to add a `data` argument to `autolayer()`, much in the same way that `autoplot()` is used.

**Comment by mitchelloharawild** [comment]
Added. This will be included in the next release (coming in a few days).
