### ISSUE TITLE
hilo should be a record type

### ISSUE THREAD

**Issue by earowang** [tidyverts/fabletools#116]
See https://vctrs.r-lib.org/articles/s3-vector.html#record-style-objects

**Comment by mitchelloharawild** [comment]
Do you know how this works with unnesting?
Is there some way to specify unnesting behaviour for a record?

I presume you prefer the record type because it is more efficient for the common tasks of hilo?

**Comment by earowang** [comment]
Casting to a list using `as.list()`?

**Comment by mitchelloharawild** [comment]
Which gives a wide expansion? Perhaps I'll have to experiment.

**Comment by earowang** [comment]
We can define `vec_cast(x = <hilo>, to = <list_of>)` to give a wide expansion. If you mean a wide expansion is 
``` r
unclass(as.POSIXlt(Sys.Date() + 0:9))
#> $sec
#>  [1] 0 0 0 0 0 0 0 0 0 0
#> 
#> $min
#>  [1] 0 0 0 0 0 0 0 0 0 0
#> 
#> $hour
#>  [1] 0 0 0 0 0 0 0 0 0 0
#> 
#> $mday
#>  [1] 11 12 13 14 15 16 17 18 19 20
#> 
#> $mon
#>  [1] 8 8 8 8 8 8 8 8 8 8
#> 
#> $year
#>  [1] 119 119 119 119 119 119 119 119 119 119
#> 
#> $wday
#>  [1] 3 4 5 6 0 1 2 3 4 5
#> 
#> $yday
#>  [1] 253 254 255 256 257 258 259 260 261 262
#> 
#> $isdst
#>  [1] 0 0 0 0 0 0 0 0 0 0
#> 
#> attr(,"tzone")
#> [1] "UTC"
```

<sup>Created on 2019-09-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mitchelloharawild** [comment]
How do you expect this to work with multivariate distributions?
Perhaps a new class for multivariate hilo objects which are a list of `hilo` objects would be better than what we currently do?
