### ISSUE TITLE
fcdist should be a list-of subclass

### ISSUE THREAD

**Issue by earowang** [tidyverts/fabletools#117]
See https://vctrs.r-lib.org/reference/new_list_of.html

`.env` should be an attribute associated with `list-of`.

**Comment by mitchelloharawild** [comment]
Great, thanks.

**Comment by earowang** [comment]
I’d suggest to leave vctrs for v0.2.0 release. we need more formal
definitions for these custom classes.

**Comment by mitchelloharawild** [comment]
Are you sure that fcdist should be a list-of? I agree that `.env` should be an attribute, but I'm not sure that all elements of the list will necessarily be the same class.

**Comment by earowang** [comment]
I'm sure it's not a vctrs type. We'll go through the vctrs definitions 
when the thesis is done.

**Comment by mitchelloharawild** [comment]
While a `list_of` class is reasonable, I think it will be unnecessarily slow. As distribution methods support vectorisation, needing to dispatch on each element of the vector (as would be done in a `list_of`) may be expensive.

Looking forward to talking about this one soon, as it will direct development of #123

**Comment by mitchelloharawild** [comment]
Closing as forecast distributions will be implemented in the https://github.com/mitchelloharawild/distributional package.
