### ISSUE TITLE
Use distributions3 package instead of fcdist class

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/fabletools#123]
The `fabletools` package currently provides a limited set of distributions (`fcdist` class) for forecasts: `dist_normal()`, `dist_mv_normal()`, `dist_sim()`, `dist_unknown()` (and the ability to add more via `new_fcdist()`). They support the calculation of forecast intervals (like `quantile()`), arbitrary transformations, and have some nice minimal display methods. Eventually it would be many other common distributions should be added.

Instead, it would be nice if `distributions3` could replace this distributions functionality.
It would require some extensions to the `distributions3` package for feature parity, hopefully many of which would be useful features for learning distributions (and eventually, providing distributions in modelling packages much like fable does).

Some features required in `distributions3` to replicate the `fcdist` functionality include:
* Transformed distributions (for arbitrary transformations and distributions)
* Fix distributions length attributes (ideally use `vctrs`) for table support
* Minimal print methods for tabular displays
* Support for different distributions in the same vector

I think this wishlist would require some substantial refactoring of `distributions3` object classes to achieve. I'd be happy to help with the implementation of this (I'd be doing similar refactoring anyway to modify `fcdist` for `vctrs` support.)

We could also consider moving `hilo` objects into the package, although that can happen later if we define `hilo.distribution()` in `fabletools`.

@earowang - what do you think of this change?
@alexpghayes - would this functionality be welcomed in `distributions3`?

**Comment by alexpghayes** [comment]
I'm onboard! Won't be able to contribute to these changes myself, I'm swamped. There's some discussion in #38 that might be useful.
