### ISSUE TITLE
Request for Forecast Accuracy

### ISSUE THREAD

**Issue by yijunwang0805** [tidyverts/fabletools#130]
Hi Mitchell,

Good morning!

I am using the ```accuracy``` command. And I realize two things.

Currently, the ```accurarcy``` command yields the table with ```ME```, ```RMSE```, ```MAE```, ```MPE```, ```MAPE```, ```MASE```, ```ACF1```

```r
# A tibble: 1 x 9
  .model .type       ME  RMSE   MAE   MPE  MAPE  MASE   ACF1
  <chr>  <chr>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>
1 ets    Training 0.321  15.8  12.0 0.103  2.87 0.752 -0.177
```
1) However, ```MPE``` ```MAPE``` could yield ```NaN``` or ```Inf``` if the outcome of interest was ```0``` or a very small number like ```0.01```.  (Particularly for retail stores, ```0``` is very common.) I am not sure how to deal with this issue, I guess it is what it is. But I think we could handle the second one.

2) ```RMSE``` is the root mean standard error, and ```MAE``` is the mean absolute error, which will be blown up by extreme sales. This happens almost every month when there is a huge customer who comes to the retail store to buy lots of stuff. From a practical viewpoint, the root median standard error would give better insight. 

This package and feature are absolutely fabulous. What I mention is a pretty minor thing. But I think it would be great to let you know there is such a practical issue.

**Comment by mitchelloharawild** [comment]
>     1. However, `MPE` `MAPE` could yield `NaN` or `Inf` if the outcome of interest was `0` or a very small number like `0.01`.  (Particularly for retail stores, `0` is very common.) I am not sure how to deal with this issue, I guess it is what it is. But I think we could handle the second one.

`MPE` and `MAPE` are percentage errors, and should not be used to evaluate data with low counts. This is simply a limitation of the measure, which can be overcome by looking at a better measure such as `MASE`.

>     2. `RMSE` is the root mean standard error, and `MAE` is the mean absolute error, which will be blown up by extreme sales. This happens almost every month when there is a huge customer who comes to the retail store to buy lots of stuff. From a practical viewpoint, the root median standard error would give better insight.

`RMSE` and `MAE` are widely used accuracy measures, and have therefore been included as defaults. If you're interested in using root median standard error, then you can define it yourself.

```r
root_median_squared_error <- function(.resid, na.rm = TRUE, ...){
  sqrt(median(.resid^2, na.rm = na.rm))
}
accuracy(fit, measures = root_median_squared_error)
```

> 
> This package and feature are absolutely fabulous. What I mention is a pretty minor thing. But I think it would be great to let you know there is such a practical issue.

:bee: :smile: 
Happy to hear it.

**Comment by yijunwang0805** [comment]
Hi Mitchell,

I try to replicate what you wrote above. 

```r
  library(fable)
  library(tsibble)
  library(tsibbledata)
  library(dplyr)
  
  fit <- aus_production %>%
    filter(Quarter < yearquarter("2006 Q1")) %>% 
    model(ets = ETS(log(Beer) ~ error("M") + trend("Ad") + season("A")))
  
  # In-sample training accuracy does not require extra data provided.
  accuracy(fit)
  
  # Out-of-sample forecast accuracy requires the future values to compare with.
  # All available future data will be used, and a warning will be given if some
  # data for the forecast window is unavailable.
  fc <- fit %>% 
    forecast(h = "5 years")
  fc %>% 
    accuracy(aus_production)
  
  # It is also possible to compute interval and distributional measures of
  # accuracy for models and forecasts which give forecast distributions.
  fc %>% 
    accuracy(
      aus_production,
      measures = list(interval_accuracy_measures, distribution_accuracy_measures)
    )
  
  root_median_squared_error <- function(.resid, na.rm = TRUE, ...){
    sqrt(median(.resid^2, na.rm = na.rm))
  }
  accuracy(fit, measures = root_median_squared_error)
 ```
However, there is an error which I don't know how to fix it.
```r
Error in squash(measures) : 
  VECTOR_ELT() can only be applied to a 'list', not a 'closure'
```

**Comment by mitchelloharawild** [comment]
Hmm, guess it needs to be in a named list.
```r
accuracy(fit, measures = list(rmse = root_median_squared_error))
```

This probably needs improving.
