### ISSUE TITLE
new_transformation without taking the log

### ISSUE THREAD

**Issue by yijunwang0805** [tidyverts/fabletools#132]
Hi Mitchell,

Good afternoon!

I have been using your package ```fasster``` for a couple of months. The forecast results went really well. And I am really happy - thanks to you! 

I try to refine the process and want to set the forecast between a lower bound and upper bound. In some cases, ```FASSTER``` would return negative values. However, in the sales industry, things should be 0 or positive!

I see there is the ```new_transformation``` function for scaled logit with bound form otexts. [https://otexts.com/fpp3/transformations.html](url)

But what if I can't take the log? (Sales have a lot of data with 0 so I can't take log(y). I also try log(y + 1), but it tends to underestimate for some reason.) **How to limit forecast within bounds without taking the log?**

I look over your code on ```fabletools``` [https://github.com/tidyverts/fabletools/blob/master/R/transform.R](url), but I don't know how to do this. Could you please help me with this?

**Comment by robjhyndman** [comment]
You could try log(x+c) for some small c. Experiment to find an appropriate value.

**Comment by mitchelloharawild** [comment]
You can create any transformation for use within fable by specifying the transformation function and its inverse via `new_transformation()`.

As for which transformations are useful for bounding sales data containing 0, I'll have to direct you to other sources of help such as [CrossValidated](https://stats.stackexchange.com/)

**Comment by yijunwang0805** [comment]
Thank you all! Will do
