### ISSUE TITLE
Implement other reconciliation methods

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/fabletools#142]
CC @GeorgeAthana 

- [x] `bottom_up()`
- [x] `top_down()`
- [x] `middle_out()`

**Comment by mitchelloharawild** [comment]
Potential interfaces, opinions encouraged.

`top_down(lst_mdl, method = c("average_proportions", "proportion_averages", "forecast_proportions"), data = NULL)`

`data` must be included when using `average_proportions` or `proportion_averages`. Not sure about the naming and default method here.

`middle_out(lst_mdl, upper = bottom_up(...), lower = top_down(...), split = 2)`

Presumably with the concept of disjoint hierarchies, it is reasonable to accept any reconciliation method for the upper and lower halves of a `middle_out()` reconciliation process. I'm not sure how best to handle options to the `upper`/`lower` methods here. Also there may be nicer ways to specify the level of the split. I've intentionally avoided using `level` here to minimise confusion with confidence levels, if there is a better name let me know.

**Comment by robjhyndman** [comment]
`forecast_proportions` would be the best default for `top_down` as it works much better than the other two.

Both `top_down` and `middle_out` should give errors if the structure is not a pure hierarchy.

The `split` could perhaps be specified as a character string based on the `aggregate_key`.
