### ISSUE TITLE
Yardstick for time series

### ISSUE THREAD

**Issue by alexhallam** [tidyverts/fabletools#145]
Hi, I have been thinking a lot about distributional error metrics like pinball loss and CRPS. I saw that CRPS is part of fabletools. I would be interested on working on a separate packages which was purely focused on calculating time series distributional error metrics -- a package like yardstick. 

I was curious what your thoughts were. Though it makes sense to me to decouple distributional error metrics and fabletools I am guessing that you have a good reason for not doing that. What are your thoughts? Would you have interest in working on something like this?

**Comment by mitchelloharawild** [comment]
Separate package(s) for accuracy measures makes sense to me. I don't know how necessary a distributional accuracy package is, as I don't know of too many distributional accuracy measures.

When you say yardstick for time series, I don't see the need for catering specifically to time series. The accuracy measures in fabletools aren't necessarily time series specific, and a cohesive interface between cross sectional and time series would be nice.

I think a prerequisite for a package like this would be better distribution objects, suitable for prediction outputs for both cross-sectional and time series models. I am working on writing distribution objects with vctrs now.

**Comment by alexhallam** [comment]
> Separate package(s) for accuracy measures makes sense to me. I don't know how necessary a distributional accuracy package is, as I don't know of too many distributional accuracy measures.

Yeah, you are right. I don't think it has to be distributional only. 

I do think that there are error metrics that don't really matter for forecasters though. For example, I can't think of a situation where AUC means much to forecasters. 

I think that yardstick is a really good package for cross sectional data. I use the package for `mape()` and I contributed the `mase()` function. I don't use my own `mase()` function from `yardstick` though. I prefer to use `mase()` from `forecast` because `forecast` knows if `mase()` should be seasonal or non-seasonal -- because of the frequency of the ts object. This has lead to a workflow where I go to: 1.) `forecast` for `mase`, 2.) custom functions for pinball loss, and 3.) use `rsample::rolling_orgin()` with `yardstick` for `mae()` and `mape()`.

I think the patchwork of packages I use to get time series error metrics may vindicate a package which would make my workflow easier, but alternatives may already exist which makes this easy and I just don't know about it. I am curious what you think.

-------

If you are looking for a volunteer to help with using `vctr()` to make distribution objects let me know. I am happy to work on open issues.

**Comment by mitchelloharawild** [comment]
Regarding distribution objects, the repo for this package public: https://github.com/mitchelloharawild/distributional

If you wanted to help, comments/opinions/critique of the package would be useful.
The aim of the package is for it to be used in the return output of model predictions, but also be useful for other purposes such as specifying priors and teaching distributions.

**Comment by mitchelloharawild** [comment]
This should now be very achievable as distributional is maturing.
However I don't know of enough distributional accuracy measures to warrant a package. If you'd like to put one together, feel free to take code from the distributional accuracy measures in fabletools.
