### ISSUE TITLE
accuracy fails when using a attempting to validate multiple test datasets

### ISSUE THREAD

**Issue by jstammers** [tidyverts/fabletools#162]
I'm trying to cross-validate a model across multiple forecast horizons. 
My approach involves forecasting ahead a fixed amount and creating mutliple test datasets using `stretch_tsibble`.

When trying to score the forecasts using `accuracy`, I receive the following error,
```r
Error: The result is not a valid tsibble. Do you need `as_tibble()` to work with data frame?
```
This can be reproduced using 
```r
library(fable)
library(fabletools)
library(tsibble)
library(tsibbledata)
aus_train <- aus_retail %>% filter(Month < '1990-01-01', `Series ID` == 'A3349849A')
aus_test_cv <- aus_retail %>% stretch_tsibble(.init=30,.step=10)
aus_model <- aus_train %>% model(ets = ETS(Turnover))
aus_test_acc <- aus_model %>% forecast(h="1 year") %>% accuracy(aus_test_cv)
```
Where the last line will result in the above error. Specifiying columns to join on using `by` does not make any difference.

Is this related to #158?

**Comment by mitchelloharawild** [comment]
In your code you've fitted a model to a single fold of the data (`aus_train`), and then attempted to compare the resulting 1 year of forecasts against folds of the entire data.

Cross-validation of a model requires refitting that model on multiple folds of the data, and then comparing its forecasts against actual data. More details can be found here: https://otexts.com/fpp3/tscv.html
