### ISSUE TITLE
Pass specials via `.specials` not `specials`

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/fabletools#166]

**Comment by davidtedfordholt** [comment]
This seems tedious, so I'm very interested in completing it. `specials` seems to be used in three ways, as far as I can see. It's a list inside the `self` object. It is also an object internal to a number of functions, usually created with `parse_model_rhs()`. It is also a parameter in a number of functions. 

I don't want to guess at which of those three you want changed. The first seems obvious that you would. I would probably default to the first and third, but that's a loosely held thought.

**Comment by davidtedfordholt** [comment]
To be explicit about it, I'm very aware that it'll take, at a minimum, combing through `fabletools`, `fable`, `fasster`, `fable.prophet` and `fable.bsts`. Seems better to do it earlier, rather than later, and it's an excuse to get better acquainted with the way specials are being passed around, anyway.

**Comment by mitchelloharawild** [comment]
Pretty tedious task, but potentially valuable. Definitely something to have finished for the next release of fabletools.

Ideally fabletools would be updated to pass the specials to both `.specials` and `specials`, as to not break CRAN versions of fable and feasts. Then in the next release of fable/feasts, their methods will be updated to use `.specials` instead of `specials`. This is a bit tricky as some of these functions will pass through `...` to functions that won't catch `specials` as an argument, so some identification of formals for subsequent methods is needed. Alternatively we could make simultaneous releases of fable, feasts, and fabletools (but this can get tricky with CRAN).

I think its best to keep `specials` within `self` as it is, because this doesn't conflict with the model function's argument `specials`. Additionally it creates some disambiguation between the set of specials functions (`self$specials`), and the specials computed on the data (`specials`). The goal of this is to allow model functions to use `specials` as an argument.

Generally speaking, the argument `specials` is used whenever new data is provided to the model. So this includes the model training method, `forecast()`, `generate()`, `refit()`, `stream()`, and `interpolate()`. If you're using the RStudio IDE, the Ctrl/Cmd + Alt/Option + Shift + M shortcut will be handy for renaming variables within scope.

**Comment by davidtedfordholt** [comment]
That makes sense to me. I assume the “rightest” way to go about it might be to implement `lifecycle::deprecate_warn`. Which I’m happy to do.

**Comment by mitchelloharawild** [comment]
I think its okay to silently deprecate this one, as the interface doesn't face regular users (only developers, who will all know about this change).

**Comment by mitchelloharawild** [comment]
Closing as this is not worth the development effort, especially needing to change the model methods.
