### ISSUE TITLE
`$<-.mdl_df` does not update attributes

### ISSUE THREAD

**Issue by Hong-Revo** [tidyverts/fabletools#167]
Is there a documented way of doing this? I did

```r
mods$model_name <- NULL
```

which resulted in an error. I found that I needed to modify the `models` attribute of the mable object as well as removing the column of model objects.

**Comment by mitchelloharawild** [comment]
Removing a model from a mable is currently done with `select()`.

**Comment by Hong-Revo** [comment]
Thanks, that worked. It might be worth mentioning this somewhere in the docs -- not sure where though.
