### ISSUE TITLE
Suggestion: add response_var/forecast_var utility functions

### ISSUE THREAD

**Issue by Hong-Revo** [tidyverts/fabletools#169]
Much like `key_vars` and `index_var` for a tsibble, `response_var` would return the response variable name for a mable, and `forecast_var` would return the forecast variable name for a fable. It's possible these exist already and I haven't found them.

**Comment by mitchelloharawild** [comment]
Sounds good.

**Comment by mitchelloharawild** [comment]
Closing as `response_vars()` and `distribution_var()` have been added.
