### ISSUE TITLE
pkgdown site doesn't include vignettes

### ISSUE THREAD

**Issue by Hong-Revo** [tidyverts/fabletools#171]
I guess this is just an oversight, but fabletools.tidyverts.org doesn't link to the vignettes, while fable.tidyverts.org does.

![image](https://user-images.githubusercontent.com/11328890/76133999-45208800-5fe9-11ea-92ac-68cdf4f7c101.png)

![image](https://user-images.githubusercontent.com/11328890/76134006-5073b380-5fe9-11ea-94b4-eb42c52021da.png)

**Comment by mitchelloharawild** [comment]
There aren't any vignettes in the released version of fabletools.

The dev version website can be found at http://fabletools.tidyverts.org/dev

**Comment by mitchelloharawild** [comment]
That being said, the 'release' version of the site isn't right. Will be
fixed when a patch is released next week.
