### ISSUE TITLE
Model combination error message

### ISSUE THREAD

**Issue by brshallo** [tidyverts/fabletools#197]
Watched @mitchelloharawild [presentation](https://www.youtube.com/watch?v=DhDOTxojQ3k&t=913s). Was exploring model ensembles and combinations. Would prefer a more informative error message when trying something like:

``` r
library(tsibble)
library(fable)
library(tidyverse)

tsibble::tourism %>% 
  group_by(Purpose) %>% 
  summarise(Trips = sum(Trips)) %>% 
  model(ets_n = ETS(Trips ~ trend("N")),
        ets_a = ETS(Trips ~ trend("A"))) %>% 
  mutate(combn = (ets_n * 0.25 + ets_a * 0.75))
#> Error: A mable can only contain models with the same response variable(s).
```

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

that perhaps mentions using `combination_model()` or `combination_ensemble()` for more sophisticated combinations.

(Would also love a vignette documenting how to implement arbitrary weightings.)

**Comment by mitchelloharawild** [comment]
The relevant issue for this is https://github.com/tidyverts/fabletools/issues/101, this code should work without issue.
