### ISSUE TITLE
Error: A model specification is trained to a dataset using the `model()` function.

### ISSUE THREAD

**Issue by Vidaringa** [tidyverts/fabletools#206]
I'm having a trouble when using model() without 'specials'.

I'm able to follow the examples here (https://www.mitchelloharawild.com/blog/fable/) without any problem, i.e.

    fit <- tourism_aus %>% 
      model(auto_ets = ETS(Trips))

When using my own data I get the error messages in the title.

    unemp_ts <- unemp_hist %>% 
        select(date, kyn, heiti, atvinnuleysi) %>% 
        as_tsibble(key = c("kyn", "heiti"), index = date) %>% 
        fill_gaps(atvinnuleysi = 0)

    # Doesn't work
    fit <- unemp_ts %>% 
        model(
            ets_auto = ETS(atvinnuleysi)
    )

    # Works fine
    fit <- unemp_ts %>% 
        model(
            ets_auto = ETS(atvinnuleysi ~ trend("A"))
    )

I want to use the former i.e. not specifying specials. What am I doing wrong?

Note, I get the same error message no matter what method I use (ARIMA, SNAIVE, ...)

Here is a view of my data

    # A tsibble: 1,452 x 4 [1M]
    # Key:       kyn, heiti [4]
        date kyn   heiti       atvinnuleysi
       <mth> <chr> <chr>              <dbl>
     1 1990 jan. Karl  Íslendingur       0.0227
     2 1990 feb. Karl  Íslendingur       0.0231
     3 1990 mar. Karl  Íslendingur       0.0260
     4 1990 apr. Karl  Íslendingur       0.0254
     5  1990 maí Karl  Íslendingur       0.0291
     6 1990 jún. Karl  Íslendingur       0.0211
     7 1990 júl. Karl  Íslendingur       0.0149
     8 1990 ágú. Karl  Íslendingur       0.0177
     9 1990 sep. Karl  Íslendingur       0.0161
    10 1990 okt. Karl  Íslendingur       0.0140

**Comment by mitchelloharawild** [comment]
Do you have a data frame called `atvinnuleysi` in your environment?
If so, this has been fixed in the development version of fabletools (https://github.com/tidyverts/fabletools/issues/201)

**Comment by Vidaringa** [comment]
Yes I have and when I removed it everything works!

Thanks a lot
