### ISSUE TITLE
aggregate_key() fails with dplyr 1.0

### ISSUE THREAD

**Issue by JS1612** [tidyverts/fabletools#211]
Returns `"Error: `vars` must be a character vector."`
Think this may be due to the following change in dplyr 1.0:
`".grouped_df now regroups to respect any grouping columns that have been removed (#4708)."`

**Comment by mitchelloharawild** [comment]
This has been fixed in the development version of fabletools, which you can install with `remotes::install_github("tidyverts/fabletools")`. This version is ready for submission to CRAN, but is awaiting the release of vctrs 0.3.1.
