### ISSUE TITLE
Allow new_transformation() to accept dynamic values

### ISSUE THREAD

**Issue by dannymorris** [tidyverts/fabletools#212]
The scaled_logit transformation from[ fpp3 website](https://otexts.com/fpp3/forecasting-using-transformations.html) seems to require hard coded values for the lower and upper constraints. This limits the usefulness of this transformation, especially if you're fitting models to tsibbles with multiple keys for which the series values are on different scales. A better option would be to allow the scaled_logit transformation to accept dynamic lower and upper constraints, e.g. the min and max of the time series for each key. 

```
# function to constrain predictions to lie within interval
scaled_logit <- fabletools::new_transformation(
  transformation = function(x, lower=0, upper=1){
    log((x-lower)/(upper-x))
  },
  inverse = function(x, lower=0, upper=1){
    (upper-lower)*exp(x)/(1+exp(x)) + lower
  }
)

# sample tsibble
sample_tsibble <- tsibble::tsibble(
  date = as.Date("2017-01-01") + 0:9,
  value = rnorm(10)
)

# apply scaled_logit transformation, where lower = min(value) and upper = max(value)
# this does not work
sample_tsibble %>%
  fabletools::model(
    arima = ARIMA(scaled_logit(value, min(value)-1, max(value)+1))
  )

# Error: Could not identify a valid back-transformation for this transformation.
# Please specify a valid form of your transformation using new_transformation()

# hard coded values work
sample_tsibble %>%
  fabletools::model(
    arima = ARIMA(scaled_logit(value, -5, 5))
  )

> packageVersion("fable")
[1] ‘0.2.0’
> packageVersion("fabletools")
[1] ‘0.1.3’
```

**Comment by dannymorris** [comment]
This may be related to #207

**Comment by mitchelloharawild** [comment]
This is an issue with how variable inputs are passed to `scaled_logit()`, and the error is fortunately being captured from a check that `inverse(transform(x)) == x`

Essentially, it is using `inverse(x, min(x) - 1, max(x) + 1)`, however at this stage `x` is now on the transformed scale. This gives incorrect (varied) bounds for the inverse.

Perhaps the transformation parsing algorithm could check the length of parameters, and if they are length 1 they can be assumed as fixed inputs to the transformation function which should be stored for later use.

**Comment by mitchelloharawild** [comment]
Closing as on further consideration I think this is behaviour can be expected and possibly useful for some transformations. However the concept of 'training a transformation' on some data which produces parameters that are used for forecasting is an interesting one which can be explored more later. This is related to the issue of `forecast::BoxCox(y, lambda = "auto")`, were the transformation parameter is estimated from `y`, and then stored for later use when back-transforming the forecasts.

Identifying if the length of an argument is 1, and then trying to do something clever with it will likely produce more confusing issues in the future. An alternative to being smart here is requiring a declaration that this is some fixed parameter, for example: `ARIMA(scaled_logit(value, fixed(min(value)-1), fixed(max(value)+1)))`
