### ISSUE TITLE
Backtransformation seems to cause performance issues on untransformed forecasts

### ISSUE THREAD

**Issue by TimothyHyndman** [tidyverts/fabletools#213]
I think the [back-transformation code in forecast.mdl_ts ](https://github.com/tidyverts/fabletools/blob/7ee7681106554525a5cc6b4697f2e5eb191bfd11/R/forecast.R#L179) is taking up a lot of time compared to the rest of the forecast function. 

In the below example, calls to map() from forecast.mdl_ts take up ~75% of the time. 

Given that there is no transformation here, can we skip the expensive back-transformation?

```{r}
library(fable)

data <- tsibble::tsibble(
  date = rep(as.Date(c("2000-01-01", "2001-01-01", "2002-01-01")), 26),
  value = rep(c(1,2,3), 26),
  blah = rep(letters, each = 3),
  key=blah,
  index=date
)

fit <- data %>% model(MEAN(value))


profvis::profvis({
  fit %>% forecast()
})
```

**Comment by mitchelloharawild** [comment]
When I run this, a non-measured (<10ms) time is spent on this code. Calls to map() take up 75% of the time, but this is from the `map2()` in `forecast.lst_mdl()` (which is the entire forecasting step).

The slowest parts seem to be generating the future dataset, adding the distribution column to the output, and creating the fable data structure. These all can and should be made faster, but are more difficult than skipping transformations. Using transformations is also done conditionally here: https://github.com/tidyverts/fabletools/blob/7ee7681106554525a5cc6b4697f2e5eb191bfd11/R/forecast.R#L200-L203

**Comment by TimothyHyndman** [comment]
![Screenshot from 2020-06-05 21-25-14](https://user-images.githubusercontent.com/25498098/83871381-4e013100-a773-11ea-8811-8361c50b05f1.png)

Sorry this is a little clunky... here's a screenshot of my profiling results. Maybe I'm reading it wrong (and apologies if so), but I'm looking at the line directly beneath forecast.mdl_ts.

**Comment by mitchelloharawild** [comment]
Looks like it is taking a while to compute the mean of the distribution.
Could you benchmark this?
``` r
library(distributional)
dist <- dist_normal(1:10, abs(rnorm(10)))
bench::mark(
  mean(dist)
)
#> # A tibble: 1 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 mean(dist)   53.1µs     58µs    16309.        NA     18.9
```

<sup>Created on 2020-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by TimothyHyndman** [comment]
``` r
library(distributional)
dist <- dist_normal(1:10, abs(rnorm(10)))
bench::mark(
  mean(dist)
)
#> # A tibble: 1 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 mean(dist)   8.57ms    8.9ms      110.     250KB     16.4
```

<sup>Created on 2020-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mitchelloharawild** [comment]
Odd, for some reason it is taking much longer on your computer. Are you using the latest version of distributional with latest CRAN versions of vctrs and rlang?

**Comment by TimothyHyndman** [comment]
Looking much better now

``` r
library(distributional)
dist <- dist_normal(1:10, abs(rnorm(10)))
bench::mark(
  mean(dist)
)
#> # A tibble: 1 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 mean(dist)   48.7µs   52.2µs    18544.    69.7KB     23.0
```

<sup>Created on 2020-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'll check that it fixes my performance issues with MEAN later this weekend. Thanks for the help :)

**Comment by TimothyHyndman** [comment]
Just FYI I was on old github versions of vctrs, rlang, and distributional. Updated as you suggested.

**Comment by mitchelloharawild** [comment]
I expect it will be substantially faster. I'd still like the `mean()` operation to perform on the nanosecond scale, but this will need a restructuring of the distributional class.

**Comment by TimothyHyndman** [comment]
Updating seems to have fixed the performance issues related to this particular issue
