### ISSUE TITLE
Error in UseMethod("key_vars") :    no applicable method for 'key_vars' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"

### ISSUE THREAD

**Issue by edgBR** [tidyverts/fabletools#220]
Dear colleagues,

I trained 13 different models (auto_arima, ETS, arima with different fourier components, TSLM with different features and a combination model)

I have mable of 4,274 x 13 which is actually quite heavy.

I am loading my model with:

```r
models <- read_rds(path = paste0(config$LOCAL_CONFIG$DirectoryModelsOut, "ts_models.rds"))
```

Then I am generating the forecasted dataframe as follows:

```r
processed_data  <- getOriginalData() %>% 
  featureAugmentation()
future_data <- new_data(processed_data, n = opt$horizon) %>% 
  tk_augment_timeseries_signature() %>% 
  select(-c("hour", "minute", "second", "hour12", "diff", "am.pm")) %>% 
  drop_na()
```
And I have setting the indexes and keys again as:

```r
future_data <- as_tibble(future_data, key=c(x, y, z), index = snsr_dt)
```

Then I am trying to forecast as follows:

```r 
forecasted_data <- forecast(models, future_data) %>% as_fable())
```

And I am getting the following error:

```r
Error in UseMethod("key_vars") : 
  no applicable method for 'key_vars' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"
```

Does the forecast function with new_data does not support keys in the input tibble?

BR
/Edgar

**Comment by edgBR** [comment]
Hi @mitchelloharawild 

Really apologies for my sloppiness I spent the whole day today getting familiar with the drake package to wrap my code and I completely missed the typo.

Now is running but it is taking a considerable amount of time (probably because my high number of models)

BR
/Edgar

**Comment by mitchelloharawild** [comment]
No stress, hope your having some success with drake. I haven't gotten around to trying it yet but I'd like to.
4,274 x 13 models will take some time, but it is well within what we want fable to be capable of handling. When the packages are fixed on CRAN (which I've had some more success today with) I'll be working on performance improvements again.

**Comment by edgBR** [comment]
Hi @mitchelloharawild 

So far I managed to pull the basic workflow:

![drake](https://user-images.githubusercontent.com/14976422/84697053-be673980-af4d-11ea-9c2c-93bd855f4e2d.png)

However I would like to expand the models training function (basically a fable pipeline) to get the individual status of the training but I am not aware if this will be even possible.

Following on the speed "issue" I have registered a multisession backend in future but when I am producing the forecasts I can see that I am only using 1 process. It didnt happened like this when I was training. Any idea of why?

BR
/Edgar

**Comment by mitchelloharawild** [comment]
> However I would like to expand the models training function (basically a fable pipeline) to get the individual status of the training but I am not aware if this will be even possible.

What exactly do you mean by 'individual status of the training' here?

> Following on the speed "issue" I have registered a multisession backend in future but when I am producing the forecasts I can see that I am only using 1 process. It didnt happened like this when I was training. Any idea of why?

Producing forecasts aren't parallelised yet, only model fitting.
This is something which will be addressed in the performance improvements of the next release.

**Comment by edgBR** [comment]
Hi @mitchelloharawild,

Apologies I think that I should have been more specific. I would like to know what is the porgress of fitting individual models (ARIMA, ETS etc....). My first idea was going to separate this in drake steps but I don't know if fable provides out of the box features to do this.

BR
/Edgar

**Comment by mitchelloharawild** [comment]
Progress tracking can be done using the progressr package. Currently it combines models and slices of data, but I can look into separating this if progressr supports it.

**Comment by edgBR** [comment]
Well I believe that it would be useful to indetify the timings for different methods. When putting into production we usually check computational complexity as one useful metric (https://arxiv.org/pdf/1909.13316v1.pdf).

**Comment by mitchelloharawild** [comment]
Closing as the default method for `key_vars()` should be added to the tsibble package (where the generic is defined).
Workflow/timing/progress reporting can be opened as a new issue if you'd like to continue the discussion.
