### ISSUE TITLE
Unable to see mable object in RStudio IDE with fable 0.2.1

### ISSUE THREAD

**Issue by edgBR** [tidyverts/fabletools#232]
Dear colleagues,

I was trying to visualize my fable object in RStudio from the environment as well as the console- However I am getting the following error:

``` R

> View(fitting_models)
Error: Can't convert <lst_mdl> to <character>.
Run `rlang::last_error()` to see where the error occurred.
```

Running last_error:

```R

> rlang::last_error()
<error/vctrs_error_incompatible_type>
Can't convert <lst_mdl> to <character>.
Backtrace:
 1. (function (x, start, len, ...) ...
 5. vctrs::vec_default_cast(...)
 6. vctrs::stop_incompatible_cast(...)
 7. vctrs::stop_incompatible_type(...)
 8. vctrs:::stop_incompatible(...)
 9. vctrs:::stop_vctrs(...)
Run `rlang::last_trace()` to see the full context.
```
In RStudio I get the following error:

![error](https://user-images.githubusercontent.com/14976422/85547275-06f1b780-b61e-11ea-8ca4-a3041624a609.png)

However the model is displayable:

```
 fitting_models
# A mable: 3,158 x 12
# Key:     a, b, c [3,158]
   a              b      c       auto_arima     auto_arima_ex      auto_arima_red_f_1    auto_arima_red_f_2
   <chr>               <dbl>  <dbl>                 <model>                 <model>                     <model>                     <model>
 1 X             71      2 <ARIMA(0,1,1) w/ drift> <ARIMA(0,1,1) w/ drift> <LM w/ ARIMA(3,1,2) errors> <LM w/ ARIMA(0,1,1) errors>
```

Any clue about what this is happening?

**Comment by mitchelloharawild** [comment]
Thanks, I've added the `as.character()` method for this now. Could you check that it works now?

**Comment by edgBR** [comment]
Hi,

I have installed the development version and it is still not working.

BR
/Edgar

**Comment by mitchelloharawild** [comment]
This is what I see. Could you try to run this MRE?
``` r
library(fabletools)
as_tsibble(USAccDeaths) %>% 
  model(fable::ARIMA(value)) %>% 
  View()
```
![image](https://user-images.githubusercontent.com/16127127/85721710-f5e79a00-b734-11ea-96d0-a514cecf3f93.png)

<sup>Created on 2020-06-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by edgBR** [comment]
Hi,

It is working with this example but not with mine.

BR
/Edgar

**Comment by mitchelloharawild** [comment]
Do you get a different error now? `Error: Can't convert <lst_mdl> to <character>.` shouldn't be possible now.

**Comment by edgBR** [comment]
Fixed now,

There was a different error but unfortunately I didnt take the screenshot. I just reinstalled all of the packages (including the version with your last commit) and now is working.

BR
/Edgar

**Comment by mitchelloharawild** [comment]
Great, glad to hear it.
