### ISSUE TITLE
forecast() returning response variable as distribution type and .mean as point forecast

### ISSUE THREAD

**Issue by tanner-ellison** [tidyverts/fabletools#235]
the fable returned by forecast() is not naming the resulting columns as documented in the ?forecast() doc (see quote of the documentation below). 

The fable's column for dependent/response variable point forecast is returning as the distribution type with the .distribution values, instead of with the proper model's response variable name and single point values (e.g. "monthly_water_price"). The point forecast is instead being generated as column named ".mean". 

One hunch is that the default parameter for point_forecast may have changed in a recent version update as the documentation now says point_forecasts = list(.mean = mean). This issue came up in an update to the package within the last month or so.

 "Value:

     A fable containing the following columns:

        • ‘.model’: The name of the model used to obtain the forecast.
          Taken from the column names of models in the provided mable.

        • The point forecast, which by default is the mean. The name of
          this column will be the same as the dependent variable in the
          model(s).

        • ‘.distribution’. A column of objects of class ‘fcdist’,
          representing the statistical distribution of the forecast in
          the given time period."

**Comment by tanner-ellison** [comment]
duplicate of https://github.com/tidyverts/fabletools/issues/233

**Comment by mitchelloharawild** [comment]
The docs have now been updated, thanks!
