### ISSUE TITLE
augment.mdl_ts not returning distinct rows identified by key and index

### ISSUE THREAD

**Issue by tanner-ellison** [tidyverts/fabletools#238]
It appears that augment doesn't persist the key and/or index when retaining or transforming back to a tsibble

```
tsibbledata::olympic_running %>% 
aggregate_key(Length * Sex, Time = mean(Time)) %>%
model(mean = MEAN(Time), naive = NAIVE(Time)) %>% 
augment()

Error : A valid tsibble must have distinct rows identified by key and index.
ℹ Please use `duplicates()` to check the duplicated rows.
```

P.S. (I hope this is the right way to be bringing up these discoveries. I am new to github so I will appreciate any feedback needed. It happens to appear that I am looking for these because I am using this for my work and it is a breaking issue.)

**Comment by mitchelloharawild** [comment]
Yep, these are great! This was introduced by dbc5333fab1c20b0689d985d50196638096d778d, which I'm also working on fixing now. I noticed this issue when fixing #237

**Comment by mitchelloharawild** [comment]
Should be working well now. Thanks for the bug reports!
Since you asked for feedback, you may find the `reprex::reprex()` function useful for sharing code that contains errors. More details at https://www.tidyverse.org/help/
