### ISSUE TITLE
show_gap = FALSE throwing error due to column mismatch

### ISSUE THREAD

**Issue by wkdavis** [tidyverts/fabletools#241]
```r
library(tsibbledata)
library(fable)

fc <- aus_production %>%
  model(ets = ETS(log(Beer) ~ error("M") + trend("Ad") + season("A"))) %>%
  forecast(h = "3 years")

fc %>%
  autoplot(aus_production, show_gap = FALSE)
```
> Error: Distributions must have the same `dimnames` to be combined.
```r
<error/rlang_error>
Distributions must have the same `dimnames` to be combined.
Backtrace:
  1. dplyr::bind_rows(gap, object)
 12. distributional:::vec_ptype2.distribution.distribution(...)
```

Based on `rlang::last_error()` it looks like an issue in [mitchelloharawild/distributional](https://github.com/mitchelloharawild/distributional), but I'm not sure if it's actually an error there or if that's the intended behavior of `distributional:::vec_ptype2.distribution.distribution()`.

I think this is happening because `fabletools::forecast()` automatically names the distribution column to the same name as the target variable (*Beer* in my example), but in the the original dataset the target variable is a `<dbl>` vector rather than a`<dist>`, so when the default functionality is used `autoplot()` is trying to combine a `<dbl>` vector with a `<dist>` vector. This might be the intended behavior, but it makes things challenging because the error is thrown when default arguments are used for everything except `show_gap`, so it's not intuitive as to the correct way to allow `show_gap = FALSE`.

**Comment by mitchelloharawild** [comment]
Fixed, thanks!

**Comment by wkdavis** [comment]
Thank you!
