### ISSUE TITLE
unnest() not unnesting hilo forecast

### ISSUE THREAD

**Issue by sarahndippity** [tidyverts/fabletools#245]
Hello,

I noticed that after the recent fable update 0.2.0, I'm having some trouble unnesting a hilo column. I used to use `tsibble::unnest_tsibble()` which didn't work, then noticed the [recent documentation](https://fabletools.tidyverts.org/reference/forecast.html) states to use `tidyr::unnest()`, but that didn't work either. `fabletools::unpack_hilo()` works, is this the correct function to be using?

``` r
library(fable)
library(tsibble)
library(tsibbledata)
library(tidyverse)

beer_fc <- aus_production %>%
  model(ets = ETS(Beer)) %>%
  forecast(h = "1 year") %>%
  mutate(hilo_80 = hilo(Beer, level = c(80)))

# documentation states to use tidyr::unnest()
beer_fc %>% unnest(hilo_80) 
#> Error: Assigned data `map(data[[col]], as_df, col = col)` must be compatible with existing data.
#> x Existing data has 4 rows.
#> x Assigned data has 3 rows.
#> i Only vectors of size 1 are recycled.

# this works
beer_fc %>% unpack_hilo(hilo_80)
#> # A tsibble: 4 x 6 [1Q]
#> # Key:       .model [1]
#>   .model Quarter        Beer .mean hilo_80_lower hilo_80_upper
#>   <chr>    <qtr>      <dist> <dbl>         <dbl>         <dbl>
#> 1 ets    2010 Q3 N(405, 214)  405.          376.          433.
#> 2 ets    2010 Q4 N(480, 318)  480.          445.          515.
#> 3 ets    2011 Q1 N(417, 257)  417.          386.          448.
#> 4 ets    2011 Q2 N(383, 234)  383.          353.          413.
```

<sup>Created on 2020-07-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mitchelloharawild** [comment]
`unnest()` for `<hilo>` objects had to be removed in v0.2.0 of fabletools, the dplyr update v1.0.0 required us to change how `<hilo>` vectors are structured. Unfortunately we also couldn't give a nicer error message in this case.

Instead you can unpack hilo objects using `unpack_hilo()` as you've done, or a new feature is that you can access the components with `$`. For example, `beer_fc %>% mutate(lower = hilo_80$lower)`.

**Comment by sarahndippity** [comment]
Ah I see, thanks for the timely response. I can make a pull request to update the documentation, if that's alright with you. Is `unpack_hilo()` the recommended function to be using?

**Comment by mitchelloharawild** [comment]
A pull request would be great.
Both methods should always work as they are handled completely within our packages, so it is a matter of preference.
