### ISSUE TITLE
Unable to use parameter lists in transformations

### ISSUE THREAD

**Issue by TylerGrantSmith** [tidyverts/fabletools#253]
The following examples error in different ways:

``` r
library(fable)
#> Loading required package: fabletools

offset <- list()
offset$value <- 1

USAccDeaths %>%
  as_tsibble() %>%
  model(arima = ARIMA(log(value + offset$value)))
#> Error: Could not identify a valid back-transformation for this transformation.
#> Please specify a valid form of your transformation using `new_transformation()`.

USAccDeaths %>%
  as_tsibble() %>%
  model(arima = ARIMA(log(value + offset[["value"]])))
#> Error in offset[[.x]]: no such index at level 1
```

I think in the second scenario, the error occurs because of https://github.com/tidyverts/fabletools/blob/dc1fcdbf8e6e4a6e693d8bcaab56fd265216d68b/R/parse.R#L209

the comparison is of the character vector `"y"` and the symbol `y` which evaluates to `TRUE` and so `"y"` gets replaced with `.x`, which naturally leads to an error because the call becomes `offset[[.x]]`. 

 Perhaps this should be `identical(x, response)` instead of `x == response`?

**Comment by mitchelloharawild** [comment]
Thanks. I've updated it to use `identical()`  - I didn't realise that `"y" == sym("y")` returns `TRUE` so the second scenario now works.
I'm surprised that the first scenario errors, likely because of how it parses lengths of inputs it is considering `$value` as being part of the response.

**Comment by mitchelloharawild** [comment]
The first scenario errors due to the conversion of all mentions of the response variable (`value`) to `.x`.

**Comment by mitchelloharawild** [comment]
Thanks for this bug report. This should now work:

``` r
library(fable)
#> Loading required package: fabletools

offset <- list()
offset$value <- 1

USAccDeaths %>%
  as_tsibble() %>%
  model(arima = ARIMA(log(value + offset$value)))
#> # A mable: 1 x 1
#>                       arima
#>                     <model>
#> 1 <ARIMA(0,1,1)(0,1,1)[12]>

USAccDeaths %>%
  as_tsibble() %>%
  model(arima = ARIMA(log(value + offset[["value"]])))
#> # A mable: 1 x 1
#>                       arima
#>                     <model>
#> 1 <ARIMA(0,1,1)(0,1,1)[12]>
```

<sup>Created on 2021-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
