### ISSUE TITLE
How to unnest column .distribution. - class fcdist ?

### ISSUE THREAD

**Issue by lsempe77** [tidyverts/fabletools#261]
I would like to extract the SD

When I try  `data %>% unnest(x)`

Prints error:  `Error: Input must be list of vectors`

Or `data %>% unpack(.,cols=c(x))`

it prints:  `Error: Can't convert <distribution> to <integer>.`

In the past I used: `data %>% unnest_wider(.,cols=c(x))` , but it doesn't work either (`Error: Input must be list of vectors`)

Thanks!

**Comment by mitchelloharawild** [comment]
The `fcdist` class has been replaced by the distributional package - https://github.com/mitchelloharawild/distributional/.
You can extract the mean and variance of a distribution using `mean()` and `variance()`. This should be sufficient for parameterising most distributions.

There is an open issue [here](https://github.com/mitchelloharawild/distributional/issues/36) for creating a better method of extracting distribution parameters.

**Comment by lsempe77** [comment]
Thanks! `distributional::variance(x)` worked well!
