### ISSUE TITLE
Change in autoplot() for forecast + data?

### ISSUE THREAD

**Issue by EconProf** [tidyverts/fabletools#263]
I have quite a few R Notebooks (chapter summaries, exercises, projects) for my forecasting class with the first method, which now reports an error. After changing some of them to the second method I have decided that it is clearer for the students, but it would be nice if I didn't have to find and change them all. 

``` r
library(fpp3)

aus_beer <- aus_production %>% select(Beer)

aus_beer %>% 
  model(TSLM(Beer ~ trend() + season())) %>% 
  forecast(h = 12) %>% 
  autoplot(aus_beer)
#> Error in interaction(): No factors specified
  
aus_beer %>% 
  model(TSLM(Beer ~ trend() + season())) %>% 
  forecast(h = 12) %>% 
  autoplot() + autolayer(aus_beer, Beer)
```

![](https://i.imgur.com/mq1E2qY.png)

<sup>Created on 2020-09-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mitchelloharawild** [comment]
Sorry about this - should have checked the test results. Issue was introduced in previous commit 736c1f83d23578c5267fdb1aa24339fd4e691b4d.

**Comment by mitchelloharawild** [comment]
Also the package was submitted to CRAN recently, if you wanted to move back to the stable release for teaching.
