### ISSUE TITLE
Bug in bottom_up() 

### ISSUE THREAD

**Issue by GeorgeAthana** [tidyverts/fabletools#266]
tourism_full <- tsibble::tourism %>% aggregate_key((State/Region)*Purpose, Trips = sum(Trips))
tourism_fit_ets <- tourism_full %>% 
  filter(year(Quarter)<=2015) %>% 
  model(
    ets=ETS(Trips),
    ) %>% 
  reconcile(
    bu_ets = bottom_up(ets),
    wls_ols = min_trace(ets, method="ols")
    )

tourism_fc_ets <- tourism_fit_ets %>% 
  forecast(h="2 years")

tourism_fc_ets %>%  
  filter(is_aggregated(State),is_aggregated(Region),!is_aggregated(Purpose)) %>% 
  autoplot(tourism_full, level=NULL) +
  facet_wrap(vars(Purpose), scales = "free_y")

tourism_fc_ets %>%  
  filter(!is_aggregated(State),is_aggregated(Region),is_aggregated(Purpose)) %>% 
  autoplot(tourism_full, level=NULL) +
  facet_wrap(vars(State), scales = "free_y")

**Comment by mitchelloharawild** [comment]
Issue is rooted in redundant nodes, fixed in 251fcc22e9ad76fee0a0f62def2835f0d3ff62bc
