### ISSUE TITLE
TSLM to follow lm 

### ISSUE THREAD

**Issue by robjhyndman** [tidyverts/fabletools#276]
In `lm()` a `.` on the RHS of a formula indicates all available predictors. It would be good if `TSLM()` used the same syntax.

``` r
library(fable)
#> Loading required package: fabletools
library(tidyverse)
df <- tibble(
  t = seq(100),
  y = rnorm(100),
  x = factor(sample(1:3, 100, TRUE)),
  z = runif(100)
)
lm(y ~ t + x + z, data = df)
#> 
#> Call:
#> lm(formula = y ~ t + x + z, data = df)
#> 
#> Coefficients:
#> (Intercept)            t           x2           x3            z  
#>    0.215346     0.002075     0.090146    -0.325975    -0.428667
lm(y ~ ., data = df)
#> 
#> Call:
#> lm(formula = y ~ ., data = df)
#> 
#> Coefficients:
#> (Intercept)            t           x2           x3            z  
#>    0.215346     0.002075     0.090146    -0.325975    -0.428667
lm(y ~ . - x - t, data = df)
#> 
#> Call:
#> lm(formula = y ~ . - x - t, data = df)
#> 
#> Coefficients:
#> (Intercept)            z  
#>      0.2683      -0.4631


df %>%
  as_tsibble(index = t) %>%
  model(
    all = TSLM(y ~ t + x + z),
    all2 = TSLM(y ~ .),
    onlyz = TSLM(y ~ . - x - t),
  )
#> Warning: 1 error encountered for all2
#> [1] '.' in formula and no 'data' argument
#> Warning: 1 error encountered for onlyz
#> [1] '.' in formula and no 'data' argument
#> # A mable: 1 x 3
#>       all         all2        onlyz
#>   <model>      <model>      <model>
#> 1  <TSLM> <NULL model> <NULL model>
```

<sup>Created on 2020-09-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mitchelloharawild** [comment]
This is an issue with all models that accept exogenous regressors. I think the most appropriate fix for this is to write a new version of `model.frame()` which respects the scoping necessary for handling specials and data.

**Comment by wkdavis** [comment]
This would be very useful functionality to have. This was my goal in opening tidyverts/fable#195, but perhaps `fabletools` is the proper home for it.

**Comment by mitchelloharawild** [comment]
Thanks @wkdavis for bringing up this issue in {fable}. My opinions still stand on the usage of `.`, however I do now think that it should be provided as an option (as is expected from a formula interface), but discouraged due to the surprising behaviour it can have.

**Comment by mitchelloharawild** [comment]
This should work now. My stance on discouraging this interface still stands, as it can interfere with the handling of `na.action`
For example, `y ~ . - x - t` will not be the same as `y ~ z` if `x` or `t` contain missing values not in `z`. This however should not be an issue in fabletools, as we use `na.pass` instead of `na.omit`.

**Comment by mitchelloharawild** [comment]
These changes have currently been applied to `TSLM()` only (https://github.com/tidyverts/fable/commit/a23a1a0c8eb6d4c844f54af23939686db0e787ca), but I expect all models to transition to using xreg handling via fabletools for improved consistency.

Reprex:

``` r
library(fable)
#> Loading required package: fabletools
library(tidyverse)
df <- tibble(
  t = seq(100),
  y = rnorm(100),
  x = factor(sample(1:3, 100, TRUE)),
  z = runif(100)
)
lm(y ~ t + x + z, data = df)
#> 
#> Call:
#> lm(formula = y ~ t + x + z, data = df)
#> 
#> Coefficients:
#> (Intercept)            t           x2           x3            z  
#>    0.029118     0.003699     0.169548    -0.060762    -0.356964
lm(y ~ ., data = df)
#> 
#> Call:
#> lm(formula = y ~ ., data = df)
#> 
#> Coefficients:
#> (Intercept)            t           x2           x3            z  
#>    0.029118     0.003699     0.169548    -0.060762    -0.356964
lm(y ~ . - x - t, data = df)
#> 
#> Call:
#> lm(formula = y ~ . - x - t, data = df)
#> 
#> Coefficients:
#> (Intercept)            z  
#>      0.2759      -0.3745

df %>%
  as_tsibble(index = t) %>%
  model(
    all = TSLM(y ~ t + x + z),
    all2 = TSLM(y ~ .),
    onlyz = TSLM(y ~ . - x - t),
  )
#> # A mable: 1 x 3
#>       all    all2   onlyz
#>   <model> <model> <model>
#> 1  <TSLM>  <TSLM>  <TSLM>
```

<sup>Created on 2021-03-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
