### ISSUE TITLE
Add `quantile_score()` which accepts user-defined quantiles

### ISSUE THREAD

**Issue by robjhyndman** [tidyverts/fabletools#280]
1. This function is largely redundant as it averages over the 99 percentiles, so it gives a value that is half of CRPS. It would be more useful to have percentile scores for a user-defined list of percentiles, and the function return a vector corresponding to those percentiles.
2. I think the pinball loss should be defined as exactly twice what is currently coded. That way, the loss at 50% equals absolute error and the average loss equals CRPS.

**Comment by mitchelloharawild** [comment]
Do you think `percentile_score()` should have a different default percentiles, in addition to being user defined?

**Comment by robjhyndman** [comment]
Maybe. Returning a vector of 100 percentiles makes intuitive sense given the name but is a little unwieldy. We could rename it to quantile_score with default prob = c(0.05,0.25,0.5,0.75,0.95).

**Comment by mitchelloharawild** [comment]
I would prefer to keep `percentile_score()` and have it call `quantile_score()` for backwards compatibility with minimal cost. We can encourage use of `quantile_score()` instead.

**Comment by robjhyndman** [comment]
What did you think about changing the definition to be exactly twice what is currently coded? That way, the loss at 50% equals absolute error and the average loss equals CRPS.

**Comment by mitchelloharawild** [comment]
The definition of pinball loss or quantile score?
I've changed pinball loss here: https://github.com/tidyverts/fabletools/commit/26c689cbc3cdfc61f965e29fbc2bc56d22b9457c

**Comment by robjhyndman** [comment]
The definition of quantile_score to match pinball_loss.

**Comment by mitchelloharawild** [comment]
Done.
