### ISSUE TITLE
Allow specifying the "key" combination for autoplot

### ISSUE THREAD

**Issue by Fuco1** [tidyverts/fabletools#282]
I have a fable with two key columns in addition to `.model` but when I plot it seems that only `.model` is actually considered to distinguish the forecasts.

Now both the series are rendered using the same color which is not what I expect.  Is there any way to tell autoplot which variable combinations should result in a new color?

On the picture is a single model (expert) and the series id (720843) with two "sub-series".  Never-mind the other series, they are not important for the issue.

![](https://i.imgur.com/UVzOt8A.png)

**Comment by mitchelloharawild** [comment]
The `autoplot()` functions aim to provide a standard common graphic with minimal effort, but do not offer a lot of customisation.
For `autoplot(<fable>)`, each series will be separated by facets, and each model (`.model`) should be separated by colour.
Anything more custom can be made using the `{ggdist}` package.

Could you provide a minimally reproducible example?

**Comment by Fuco1** [comment]
Well, here I have only one model, but two series (with keys `a, 1` and `a, 2`).  Maybe since they share an element of the key they are not faceted.  Although by the header of the facet it seems like the model is also part of the facet separation.  I think it might also be because I reconstruct the mable from a tibble like this: `model_tibble %>% as_mable(key = key_vars(tsibble), model = all_of(cols))` and maybe lose some meta-data in the process (I'm doing some weirdness with the input tsibbles... which I'll probably drop because it's not worth it).

I came up with this example that I thought would correspond to my data, but it actually behaves differently and more to what you describe.  I'll need to investigate further, but it's 2am here so I'll do that tomorrow :)

    expand_grid(date = yearmonth(ymd('2020-01-01') + months(0:11)), key1 = c("a", "b", "c"), key2 = c("first", "second")) %>% {.$quantity = rnorm(72, 5, 2) + 20 * sin(1:72) ; .} %>% as_tsibble(index = date, key = c(key1, key2)) %>% {x <- .; model(x, m = MEAN(quantity), a = ARIMA(quantity)) %>% forecast %>% autoplot(x)}

(oneliner should work with just `fable` loaded).  Thanks so far, I'll let you know if I find something more!

**Comment by Fuco1** [comment]
I've changed some things and can no longer reproduce this.  I'm going to close the issue.  If you think it's relevant, feel free to reopen!
