### ISSUE TITLE
Plotting two forecasts in one plot

### ISSUE THREAD

**Issue by RuneZO** [tidyverts/fabletools#283]
I could not find a solution so I post here. Sorry if it is not the right place.

I am forecasting two different time-series and want to plot them in the same graph. They both are yearly data from the same years but are at a different level on my measure. Is it possible through autoplot?

**Comment by mitchelloharawild** [comment]
The `autoplot()` functions aim to provide a standard common graphic with minimal effort, but do not offer a lot of customisation.
For `autoplot(<fable>)`, each series will be separated by facets, and each model (`.model`) should be separated by colour.
Anything more custom can be made using the `{ggdist}` package.

Could you provide a minimally reproducible example?

**Comment by RuneZO** [comment]
Thanks for your reply. I managed to produce the plot I needed by simply using autoplot with autolayer.
