### ISSUE TITLE
mdl_df objects don't have a response attribute

### ISSUE THREAD

**Issue by wkdavis** [tidyverts/fabletools#286]
I'm not sure how much of this is intentional or not, but I think there might be some inconsistency in the response attribute. There is a `response_vars.mdl_df()` method, but `mdl_df` objects don't have a response attribute (from what I can find).

``` r
library(fable)
#> Warning: package 'fable' was built under R version 3.6.2
#> Loading required package: fabletools
#> Warning: package 'fabletools' was built under R version 3.6.2
library(tsibbledata)
#> Warning: package 'tsibbledata' was built under R version 3.6.2
m <- aus_production %>%
  model(NAIVE = NAIVE(Beer))

response_vars(m)
#> NULL
attributes(m)
#> $names
#> [1] "NAIVE"
#> 
#> $row.names
#> [1] 1
#> 
#> $key
#> # A tibble: 1 x 1
#>         .rows
#>   <list<int>>
#> 1         [1]
#> 
#> $model
#> [1] "NAIVE"
#> 
#> $class
#> [1] "mdl_df"     "tbl_df"     "tbl"        "data.frame"
attr(m, "response")
#> NULL
```

If I look at the `mable` constructors it looks like the only place a `response` is defined is in the `mdl_ts` objects.

https://github.com/tidyverts/fabletools/blob/f3d03fafe97baa76d57b574a712b067e1073a212/R/mable.R#L48-L74

I can confirm this in the `mdl_ts` object from my `mable` above.

```r
m$NAIVE[[1]]$response
#> [[1]]
#> Beer
```

If this is the case, should there be a method `response_vars.mdl_ts()` instead of `response_vars.mdl_df()`? Conversely, based on this check

https://github.com/tidyverts/fabletools/blob/f3d03fafe97baa76d57b574a712b067e1073a212/R/mable.R#L51-L53

all of the `mdl_ts` objects in a `mdl_df` must have the same response, so would it make sense, upon construction of the `mdl_df`, to add a `response` attribute at the `mdl_df` level as well?

**Comment by mitchelloharawild** [comment]
Thanks, this was an oversight. My plan when adding `response_vars()` was to bring the response variable of the mable up to the fable level, however seemingly the second part of this never was completed.

It should work now:
``` r
library(fable)
#> Loading required package: fabletools
library(tsibbledata)
m <- aus_production %>%
  model(NAIVE = NAIVE(Beer))

response_vars(m)
#> [1] "Beer"
```

<sup>Created on 2020-10-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wkdavis** [comment]
@mitchelloharawild Thanks!
