### ISSUE TITLE
Question Exogenous Regressors

### ISSUE THREAD

**Issue by Steviey** [tidyverts/fabletools#287]
Ubuntu 1.16.x
R 4.x
fabletools latest

Hello, I'm a little bit confused about the usage of external regressors.
Do 'xRegs' should have been forecasted for forecasts?

I have implementations with an error message, in case of lacking the xRegs
and without any related message:
No error:

```
myFit <- allData %>%  
	filter(id < myLimit) %>% # implizite partitionierung
	fabletools::model(
		nn4 = NNETAR((!!varname) ~ AR(p = NULL, P = 1, period = NULL) + myXreg + myXreg1 + myXreg2 + myXreg3 + myXreg4 + myXreg5 + myXreg6 + myXreg7 + myXreg8 + myXreg9,n_networks=as.numeric(params$n_networks))
	)

newData <- allData %>%  
	filter(id > myLimit)

fc <- myFit %>% fabletools::forecast(new_data=newData,times=myTimes,bootstrap=as.logical(params$bootstrap))

testRmse<-fabletools::accuracy(fc,newData)[1,'RMSE'] # test rmse
testRmse<-as.numeric(testRmse)

```
New ALgo same case (xReg in formula for fit), but with error:

```
fit.ses <- train_data %>% fabletools::model(TSLM(myFormula))
fc.ses <- fit.ses %>%
	fabletools::forecast(h = val_days)
```

Error: Problem with `mutate()` input `TSLM(myFormula)`.
x object 'myXreg' not found
Unable to compute required variables from provided `new_data`.
Does your model require extra variables to produce forecasts?
i Input `TSLM(myFormula)` is `(function (object, ...) ...`.

Thank you.

**Comment by mitchelloharawild** [comment]
Please provide a minimally reproducible example.
I have no idea what `myFormula` is, and so cannot know the source of the problem you have.

My best guess is that `myFormula = y ~ myXreg`, and so to produce forecasts you will need to provide future values of `myXreg` as you have done with `newData` in the NNETAR example.

**Comment by Steviey** [comment]
Your guess is right Mr. Oharawild. It seems that I implicitly provide xRegs for forecasts with nnetar doing...

```
newData <- allData %>%  
	filter(id > myLimit)
```

Where as I also could do this for TSLM this way...

```
futureDf <- new_data(train_data, n = val_days) %>% 
	mutate(myXreg = last(train_data$myXreg)) %>% 
	mutate(myXreg1 = last(train_data$myXreg1)) %>% 
	mutate(myXreg2 = last(train_data$myXreg2)) %>% 
	mutate(myXreg3 = last(train_data$myXreg3)) %>% 
	mutate(myXreg4 = last(train_data$myXreg4)) 

fit.ses <- train_data %>% fabletools::model(TSLM(myFormula))
fc.ses <- fit.ses %>%
	fabletools::forecast(new_data=futureDf)
```
I'm not sure yet, what would be the best strategy, but my initial question is answered. In any case it needs future xreg-data for forecasts if xregs are proposed to be used.
