### ISSUE TITLE
CRPS code vs formula

### ISSUE THREAD

**Issue by git314** [tidyverts/fabletools#292]
I have been using this package for CRPS. Everything works great! I am just curious how you got this formula. When I look at this paper 

https://cran.r-project.org/web/packages/scoringRules/vignettes/article.pdf

<img width="769" alt="PNG image" src="https://user-images.githubusercontent.com/68880879/100871774-ccaf0080-346e-11eb-9942-f20486d8ccda.png">

The formula has `m^2` in the denominator.

When I look at the code `m` is not squared. 

https://github.com/tidyverts/fabletools/blob/1fbbb7b556f02bd5e0f650e7eb68edc781b61074/R/accuracy.R#L211

Again, there is nothing wring with the results. I am just curious, from a math perspective, where the `m^2` went.

**Comment by robjhyndman** [comment]
We use `2/m * mean` not `2/m^2 * sum`
