### ISSUE TITLE
Add multi-step fitted values 

### ISSUE THREAD

**Issue by robjhyndman** [tidyverts/fabletools#294]
Similar to `forecast::fitted()` with `h`>1.

**Comment by mitchelloharawild** [comment]
Thinking about this some more, in combination with #137 - I've noticed that we're returning fitted medians for transformed models. Should we adjust these to provide fitted means?

Or possibly better, should we provide distributions (possibly as a non-default argument).

**Comment by robjhyndman** [comment]
Yes, fitted means or distributions would be preferable.

**Comment by mitchelloharawild** [comment]
Closing as added in https://github.com/tidyverts/fabletools/commit/aa872bf5d35224a643c83290e84e82d93c9d6b19, and fitted means (or better, distributions) is issue #137
