### ISSUE TITLE
generate() on training data time periods

### ISSUE THREAD

**Issue by robjhyndman** [tidyverts/fabletools#298]
I've thought some more about this and I don't think it makes sense to use fitted values + noise except for a decomposition model. It would lead to series with different properties in other situations.

For generative models (basically all models other than decomposition), it would make more sense to generate using the same initial conditions. e.g., conditioning on the first p+d observations for an ARIMA(p,d,q) model, or on the initial state vector for an ETS model.

It might be simpler to give an error when the time periods correspond to the training data and the model is not a decomposition.

**Comment by mitchelloharawild** [comment]
Closing as this is (or should be) what is done in the model methods and is not an issue with fabletools.
Where possible (if sufficient information is stored by the model), the simulations will begin from the state just prior to the requested `generate()` time period.
If the model cannot produce appropriate simulations for training data, it is up to that individual method to raise an error or warning as necessary.
