### ISSUE TITLE
forecast autoplot minor issues

### ISSUE THREAD

**Issue by EconProf** [tidyverts/fabletools#325]
Two very small issues with the switch to ggdist. When my students see a warning, the think it is something they did wrong, so minimizing them is very helpful. Every forecast autoplot now has the warning "Ignoring unknown aesthetics: colour ramp". Also, speaking of aesthetics, the thick borders on the new legend are rather out of place and distracting.

**Comment by mitchelloharawild** [comment]
Thanks for the feedback, the changes to ggdist are still very much a work in progress. I certainly am going to conditionally include the layers as needed to remove warnings related to unused colour/fill ramps, and improve performance.

**Comment by mitchelloharawild** [comment]
I've reverted these changes and will track ggdist development in the ggdist branch.

**Comment by mitchelloharawild** [comment]
These issues should now be fixed as I have conditionally included the relevant layers in v0.4.0.
