### ISSUE TITLE
common_xregs not available?

### ISSUE THREAD

**Issue by bhonz** [tidyverts/fabletools#344]
It appears to me that common_xregs() is not available.  NEWS says it was moved from fable to fabletools with 0.3.1.  I am using 0.3.2 and all other packages installed very recently.  I am getting "attempt to apply non-function" from fabletools.  Any other explanation?  Thanks for any help,

![common_xregs unavailable 1-26-22](https://user-images.githubusercontent.com/98489385/151239108-6e047135-5759-4556-89d4-8f283db528fd.png)

**Comment by mitchelloharawild** [comment]
`common_xregs` is not a function, but instead is a list of functions useful for exogenous regressors in a model. Specifically, it allows you to use `trend()`, `season()`, and `fourier()` as regression terms in a model.

**Comment by bhonz** [comment]
Thanks for your quick response and for correcting my thinking.  I am finally making some progress!
