### ISSUE TITLE
generate.mdl_df Broken link in documentation

### ISSUE THREAD

**Issue by FinYang** [tidyverts/fabletools#349]
In the description of `generate.mdl_df`, `\link` doesn't show the reference properly with backticks. I guess you have to use `\code{\link{}}`

https://github.com/cran/fabletools/blob/50ca79c1a8815c7b4eac6fa755ad5617264e6f8e/R/generate.R#L5
![image](https://user-images.githubusercontent.com/32216334/155917008-f065d671-41ca-414a-8af8-cb7219edfd0e.png)

**Comment by mitchelloharawild** [comment]
Fixed, thanks!
