### ISSUE TITLE
could not find function "parse_model_rhs"

### ISSUE THREAD

**Issue by kirram** [tidyverts/fabletools#381]
Hi @mitchelloharawild , the latest dev version doesn't seem to contain the parse_model_rhs function, which is required by fasster

**Comment by mitchelloharawild** [comment]
It's still there - https://github.com/tidyverts/fabletools/blob/e09af0caa2ef032a69efe34a522edc8d6e36b595/R/parse.R#L102-L115

There are some other dependency issues for fasster at the moment, in particular the dlm package has been archived. I hope to have the time to work on this, although there are other development priorities at the moment.
