### ISSUE TITLE
decomposition_model fail when using classical_decomposition

### ISSUE THREAD

**Issue by robjhyndman** [tidyverts/fabletools#388]
MRE:
```r
as_tsibble(USAccDeaths) |> 
  model(decomposition_model(
  classical_decomposition(value, type = "additive"),
  NAIVE(season_adjust)
))
```

**Comment by mitchelloharawild** [comment]
Also requires latest feasts fix in https://github.com/tidyverts/feasts/commit/2823121a73ff4b5e840c7df8844da73c2b8fd07c
The specification of the seasonally adjusted variable's structure wasn't appropriate - correct, but not suitable for the software design.
