### ISSUE TITLE
n_flat_spots deprecation when using feature_set(pkg = "feasts")

### ISSUE THREAD

**Issue by gordon-goodwin** [tidyverts/fabletools#391]
tsdaily_tenure |> 
  features(n_reps, feature_set(pkgs = "feasts")) yields:

Warning message:
`n_flat_spots()` was deprecated in feasts 0.1.5.
ℹ Please use `longest_flat_spot()` instead.
The deprecated feature was likely used in the fabletools package.
  Please report the issue at <https://github.com/tidyverts/fabletools/issues>.

**Comment by mitchelloharawild** [comment]
Thanks! Fixed in {feasts}.
