### ISSUE TITLE
object ‘guide_level’ is not exported by 'namespace:distributional'

### ISSUE THREAD

**Issue by amrofi** [tidyverts/fabletools#395]
I updated to R 4.4.0 and RStudio 2023.12.1 Build 402, Windows, and installed fabletools, fable, fpp3, etc. When I tried to load "library(fabletools)", it returned an error message :
object ‘guide_level’ is not exported by 'namespace:distributional'

This is the same error for loading fpp3, fable and feasts which requires fabletools.

**Comment by mitchelloharawild** [comment]
I'll be submitting a new release of fabletools shortly to resolve this issue.
For now you can install an older version of distributional with `remotes::install_github("mitchelloharawild/distributional@v0.3.1")`.

**Comment by amrofi** [comment]
Thank you so much. It worked.
You and Prof Rob Hyndman are doing a great job. 
Sincerely, Prof. Adriano Figueiredo.

**Comment by mitchelloharawild** [comment]
Thanks for your kind words, the update to fabletools has just been accepted on CRAN and binaries for Windows should be available shortly. So in a day or two (or now, if installing from sources) you can update both distributional and fabletools to resolve this issue.
