### ISSUE TITLE
Error in `autoplot()`: ! Objects of class <tbl_df> are not supported by autoplot.

### ISSUE THREAD

**Issue by Musfiqur-Rahman** [tidyverts/fabletools#396]
Error in `autoplot()`:
! Objects of class <tbl_df> are not supported by autoplot.
ℹ have you loaded the required package?
Run `rlang::last_trace()` to see where the error occurred.
Warning message:
`n_flat_spots()` was deprecated in feasts 0.1.5.
ℹ Please use `longest_flat_spot()` instead.
ℹ The deprecated feature was likely used in the fabletools package.
  Please report the issue at
  <https://github.com/tidyverts/fabletools/issues>.

**Comment by mitchelloharawild** [comment]
The dataset you are attempting to plot is not a tsibble (tbl_ts), or fable
(fbl_ts). Please check the type of the data that you are trying to use with
autoplot().
