### ISSUE TITLE
Example uses tsibbledata unconditionally

### ISSUE THREAD

**Issue by jennybc** [tidyverts/fabletools#90]
I see an error with `R CMD check` due to an example (maybe multiple examples, actually) that uses the Suggested package tsibbledata unconditionally (vs. checking if it's installed).

**Comment by mitchelloharawild** [comment]
Thanks for checking.
The tsibbledata package is used frequently throughout the examples of the package, do you know if CRAN check is performed with the suggested packages installed?

I think having examples conditional on the data package being installed will detract from the examples themselves, and that users will know that the package needs installing to run through the examples.

**Comment by jennybc** [comment]
> I think having examples conditional on the data package being installed will detract from the examples themselves, and that users will know that the package needs installing to run through the examples.

Unfortunately, I don't think this user-friendliness or realism is the top criterion for examples and CRAN regards them more like tests. To quote from [R Packages](https://r-pkgs.org/r-cmd-check.html#check-checks), yeah, I think you technically should put this code inside an `if(){ ...}`.

> **Checking for unstated dependencies in examples**. If you use a package only for an example, make sure it’s listed in the Suggests field. Before running example code that depends on it, test to see if it’s available with `requireNamespace("pkg", quietly = TRUE)`:

```
#' @examples
#' if (requireNamespace("dplyr", quietly = TRUE)) {
#'   ...
#' }
```

**Comment by mitchelloharawild** [comment]
I've had a read through the [CRAN repository policy](https://cran.r-project.org/web/packages/policies.html):

> A package listed in ‘Suggests’ or ‘Enhances’ should be used conditionally in examples or tests if it cannot straightforwardly be installed on the major R platforms. 

As the suggested packages (tsibbledata) are easily installed from CRAN for all platforms, I don't think this applies. Is that how you would read the policy?

**Comment by robjhyndman** [comment]
That's how I would read it.

**Comment by jennybc** [comment]
If you don't mind running the risk, then go for it and see what happens. I agree the examples are nicer without making them conditional on the presence of a Suggested package.

**Comment by mitchelloharawild** [comment]
On CRAN, thanks. For the record, conditional usage was required for fable/feasts when submitting fabletools as they were not yet available on CRAN (which constitutes 'straightforward installation').
