### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by mitchelloharawild** [tidyverts/fabletools#98]
The package isn't exactly 'lite' and provides many useful tools.
Is a better name fabletools? Thoughts @earowang, @robjhyndman, @GeorgeAthana?

**Comment by earowang** [comment]
Any other candidates? I don't think its "fablegenerics" though.

**Comment by GeorgeAthana** [comment]
I agree Mitch - fablelite is somewhat confusing as it is really is fableheavy :-) suggested something like "fableengine" ... I think "fabletools" is much better :-)

**Comment by mitchelloharawild** [comment]
Definitely not fablegenerics - the package does more than providing generics.
fableframework? I'm struggling with short names - I think fabletools is fine but open to other ideas.

**Comment by robjhyndman** [comment]
fabletools sounds good to me.

**Comment by mitchelloharawild** [comment]
@robjhyndman Could you add fabletools.tidyverts.org?

**Comment by robjhyndman** [comment]
Done.
